apiVersion: v1
kind: Service
metadata:
  name: harbor-internal
  namespace: harbor
  annotations:
    # Tell AWS to create an INTERNAL Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: harbor
    component: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
