apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: default
spec:
  # Parameters allow this single pipeline to handle ALL your services
  params:
    - name: git-url
      description: "Git Repository URL"
    - name: git-branch
      description: "Git Branch to clone"
      default: "main"
    - name: context-dir
      description: "Folder containing the microservice (e.g. backend/todos)"
    - name: manifest-file
      description: "K8s manifest to update (e.g. K8s/todos.yml)"
    - name: image-name
      description: "Name of the image (e.g. harbor.internal/prod/todo-service)"
    - name: image-tag
      description: "Tag for the image (e.g. commit-sha)"

  workspaces:
    - name: shared-data
      description: "Shared workspace for source code"

  tasks:
    # 1. Clone the Source Code
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: branch
          value: $(params.git-branch)

    # 2. Build and Push Image (Internal Harbor)
    - name: build-image
      taskRef:
        name: kaniko-build
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: image
          # Combine Name + Tag
          value: $(params.image-name):$(params.image-tag)
        - name: context
          value: $(params.context-dir)

    # 3. Update GitOps Repo (Trigger ArgoCD)
    - name: update-gitops
      taskRef:
        name: update-manifest
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: image
          value: $(params.image-name):$(params.image-tag)
        - name: manifest-file
          value: $(params.manifest-file)
