apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
  namespace: default
spec:
  params:
    - name: image
      description: The full tag of the image to build (e.g., harbor.internal/repo/image:tag)
    - name: context
      description: The build context path (directory containing Dockerfile)
      default: "."
    - name: dockerfile
      description: Path to the Dockerfile
      default: "Dockerfile"
  workspaces:
    - name: source
      description: Holds the source code (from git-clone task)
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.14.0
      # Kaniko needs root permissions to modify the filesystem
      securityContext:
        runAsUser: 0
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/$(params.context)/$(params.dockerfile)
        - --context=$(workspaces.source.path)/$(params.context) 
        - --destination=$(params.image)
        # Skip TLS verify since we are using internal Harbor with self-signed/no certs
        - --skip-tls-verify
