apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
  namespace: default
spec:
  params:
    - name: image
      description: The full tag of the image to build
    - name: context
      description: The build context path
      default: "."
    - name: dockerfile
      description: Path to the Dockerfile
      default: "Dockerfile"
  workspaces:
    - name: source
      description: Holds the source code
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.14.0
      securityContext:
        runAsUser: 0
      # Explicitly use the config we just mounted
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/$(params.context)/$(params.dockerfile)
        - --context=$(workspaces.source.path)/$(params.context) 
        - --destination=$(params.image)
        - --skip-tls-verify
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-creds
        items:
          - key: .dockerconfigjson
            path: config.json