apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest
  namespace: default
spec:
  params:
    - name: manifest-file
      description: Path to the yaml file relative to repo root (e.g., K8s/base/todos.yml)
    - name: new-image
      description: The new image tag to insert
    - name: branch
      description: The branch to push to (e.g., main)
    - name: git-email
      default: "tekton@example.com"
    - name: git-name
      default: "Tekton Pipeline"
  workspaces:
    - name: source
  steps:
    - name: git-update
      image: alpine/git:v2.36.3
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        - name: HOME
          value: /workspace/source
      script: |
        #!/bin/sh
        set -e
        
        # Trust the directory
        git config --global --add safe.directory $(workspaces.source.path)
        
        # Configure Git
        git config --global user.email "$(params.git-email)"
        git config --global user.name "$(params.git-name)"
        
        cd $(workspaces.source.path)
        
        # Setup remote
        ORIGIN_URL=$(git remote get-url origin)
        REPO_PATH=${ORIGIN_URL#https://}
        git remote set-url origin https://${GITHUB_TOKEN}@${REPO_PATH}
        
        # RETRY LOOP FOR PUSHING
        MAX_RETRIES=10
        COUNT=0
        
        while [ $COUNT -lt $MAX_RETRIES ]; do
          echo "Attempt $(($COUNT+1)): Pulling latest changes..."
          git pull origin $(params.branch) --rebase
          
          echo "Updating $(params.manifest-file)..."
          # Ensure we are editing the file in the new 'base' location
          sed -i "s|image: .*|image: $(params.new-image)|g" $(params.manifest-file)
          
          if git diff --quiet $(params.manifest-file); then
            echo "✅ No changes to commit."
            exit 0
          fi
          
          git add $(params.manifest-file)
          git commit -m "Deploy: Update image in base to $(params.new-image)" || true
          
          if git push origin HEAD:$(params.branch); then
            echo "✅ Successfully pushed changes to $(params.branch)."
            exit 0
          fi
          
          echo "⚠️ Push failed. Retrying..."
          COUNT=$(($COUNT+1))
          sleep 3
        done
        
        echo "❌ Failed to push after $MAX_RETRIES attempts."
        exit 1
