apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener
spec:
  serviceAccountName: pipeline
  resources:
    kubernetesResource:
      serviceType: LoadBalancer 
  triggers:
    - bindings:
      - ref: cd-binding
      template:
        ref: cd-template

        