apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: 1 # Đừng quên số lượng bản sao
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: frontend
          # BỎ "docker pull", CHỈ GIỮ LẠI ĐỊA CHỈ IMAGE
          image: k8s-harbor-harbor-e23646dd89-000fac67939de240.elb.us-east-1.amazonaws.com/prod/frontend@sha256:40fcbd541e5f03e059c5244a015eafcf0b61b506768b5e94f23810f623021d12
          ports:
            - containerPort: 80