apiVersion: v1
kind: Secret
metadata:
  name: harbor-docker-config
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiazhzLWhhcmJvci1oYXJib3ItZTIzNjQ2ZGQ4OS0wMDBmYWM2NzkzOWRlMjQwLmVsYi51cy1lYXN0LTEuYW1hem9uYXdzLmNvbTo4MCI6IHsiYXV0aCI6ICJZV1J0YVc0NlNHRnlZbTl5TVRJek5EVT0ifX19
