apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
  namespace: default
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
  workspaces:
    - name: source
      description: Holds the context and Dockerfile
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built.
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.9.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/creds/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --digest-file=$(results.IMAGE_DIGEST.path)
        - --skip-tls-verify
        - --insecure
        - --insecure-pull
        # --- Optimization: Caching ---
        - --cache=true
        - --cache-copy-layers=true
        - --cache-run-layers=true
      # --- Optimization: Resources ---
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m" # 1 CPU
        limits:
          memory: "4Gi"
          cpu: "2000m" # 2 CPUs
      securityContext:
        runAsUser: 0