apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
      description: "Nơi chứa mã nguồn"
  params:
    - name: url
      type: string
    - name: branch
      type: string
      default: "main"
  steps:
    - name: clone
      image: alpine/git:latest
      securityContext:
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -e
        # Dọn dẹp sạch sẽ workspace trước khi kéo code mới
        rm -rf $(workspaces.output.path)/*
        rm -rf $(workspaces.output.path)/.[!.]*
        echo "Đang clone branch [$(params.branch)] từ: $(params.url)"
        git clone --depth 1 -b $(params.branch) $(params.url) $(workspaces.output.path)
        echo "Clone thành công!"